spring:
  cloud:
    gateway:
      routes:
        - id: service-products
          uri: lb://service-products
          predicates:
            - Path=/gateway/products/**
          filters:
            - StripPrefix=2
            - ExampleCookie=my personalized message, user
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/gateway/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 654321
            - SetResponseHeader=Content-Type, text/plain
            - AddRequestParameter=name, diego