spring:
  cloud:
    gateway:
      routes:
        - id: service-products
          uri: lb://service-products
          predicates:
            - Path=/gateway/products/**
          filters:
            - StripPrefix=2
            - name: ExampleCookie
              args:
                message: my personalized message
                cookieName: user
                cookieValue: dscifo
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/gateway/items/**
          filters:
            - StripPrefix=2